#:schema node_modules/wrangler/config-schema.json
name = "clubtulipnco"
compatibility_date = "2026-07-08"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

[vars]
# Public parameters only
VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_51TxFB0BWG3c58XbC9Kve22jmozTy1zqOsDqpcGgaz8sxOQ0CAv4b5wTi8fxRLtXjfcs9WRzA25M1GRGENnKMCpw1006iUKpXGD"
VITE_SUPABASE_URL = "https://jkiijlqsrxczpazscbaj.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_GmawUs-8KMl6Xp_jLBxEkw_sWCh_yMy"
VITE_SUPABASE_PROJECT_ID = "jkiijlqsrxczpazscbaj"
SITE_URL = "https://club.tulipnco.com"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_GmawUs-8KMl6Xp_jLBxEkw_sWCh_yMy"
SUPABASE_URL = "https://jkiijlqsrxczpazscbaj.supabase.co"
SUPABASE_PROJECT_ID = "jkiijlqsrxczpazscbaj"
NODE_VERSION = "22"
NPM_FLAGS = "--legacy-peer-deps"
