/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppShopRouteImport } from './routes/_app/shop'
import { Route as AppPopUpsRouteImport } from './routes/_app/pop-ups'
import { Route as AppOurStoryRouteImport } from './routes/_app/our-story'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppBlogRouteImport } from './routes/_app/blog'
import { Route as AppCheckoutIndexRouteImport } from './routes/_app/checkout.index'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks.stripe'
import { Route as ApiWebhooksPopUpAnnounceRouteImport } from './routes/api/webhooks/pop-up-announce'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'
import { Route as ApiPublicMapsRouteImport } from './routes/api/public/maps'
import { Route as ApiPublicHealthzRouteImport } from './routes/api/public/_healthz'
import { Route as AppShopSlugRouteImport } from './routes/_app/shop_.$slug'
import { Route as AppCheckoutReturnRouteImport } from './routes/_app/checkout.return'
import { Route as AppBlogSlugRouteImport } from './routes/_app/blog_.$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPopUpsRoute = AppPopUpsRouteImport.update({
  id: '/pop-ups',
  path: '/pop-ups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOurStoryRoute = AppOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlogRoute = AppBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCheckoutIndexRoute = AppCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPopUpAnnounceRoute =
  ApiWebhooksPopUpAnnounceRouteImport.update({
    id: '/api/webhooks/pop-up-announce',
    path: '/api/webhooks/pop-up-announce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMapsRoute = ApiPublicMapsRouteImport.update({
  id: '/api/public/maps',
  path: '/api/public/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthzRoute = ApiPublicHealthzRouteImport.update({
  id: '/api/public/_healthz',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShopSlugRoute = AppShopSlugRouteImport.update({
  id: '/shop_/$slug',
  path: '/shop/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCheckoutReturnRoute = AppCheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog': typeof AppBlogRoute
  '/cart': typeof AppCartRoute
  '/our-story': typeof AppOurStoryRoute
  '/pop-ups': typeof AppPopUpsRoute
  '/shop': typeof AppShopRoute
  '/support': typeof AppSupportRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/checkout/return': typeof AppCheckoutReturnRoute
  '/shop/$slug': typeof AppShopSlugRoute
  '/api/public': typeof ApiPublicHealthzRoute
  '/api/public/maps': typeof ApiPublicMapsRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/webhooks/pop-up-announce': typeof ApiWebhooksPopUpAnnounceRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/checkout/': typeof AppCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog': typeof AppBlogRoute
  '/cart': typeof AppCartRoute
  '/our-story': typeof AppOurStoryRoute
  '/pop-ups': typeof AppPopUpsRoute
  '/shop': typeof AppShopRoute
  '/support': typeof AppSupportRoute
  '/': typeof AppIndexRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/checkout/return': typeof AppCheckoutReturnRoute
  '/shop/$slug': typeof AppShopSlugRoute
  '/api/public': typeof ApiPublicHealthzRoute
  '/api/public/maps': typeof ApiPublicMapsRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/webhooks/pop-up-announce': typeof ApiWebhooksPopUpAnnounceRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/checkout': typeof AppCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/blog': typeof AppBlogRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/our-story': typeof AppOurStoryRoute
  '/_app/pop-ups': typeof AppPopUpsRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/': typeof AppIndexRoute
  '/_app/blog_/$slug': typeof AppBlogSlugRoute
  '/_app/checkout/return': typeof AppCheckoutReturnRoute
  '/_app/shop_/$slug': typeof AppShopSlugRoute
  '/api/public/_healthz': typeof ApiPublicHealthzRoute
  '/api/public/maps': typeof ApiPublicMapsRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/webhooks/pop-up-announce': typeof ApiWebhooksPopUpAnnounceRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_app/checkout/': typeof AppCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unsubscribe'
    | '/blog'
    | '/cart'
    | '/our-story'
    | '/pop-ups'
    | '/shop'
    | '/support'
    | '/blog/$slug'
    | '/checkout/return'
    | '/shop/$slug'
    | '/api/public'
    | '/api/public/maps'
    | '/api/public/subscribe'
    | '/api/public/unsubscribe'
    | '/api/webhooks/pop-up-announce'
    | '/api/webhooks/stripe'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unsubscribe'
    | '/blog'
    | '/cart'
    | '/our-story'
    | '/pop-ups'
    | '/shop'
    | '/support'
    | '/'
    | '/blog/$slug'
    | '/checkout/return'
    | '/shop/$slug'
    | '/api/public'
    | '/api/public/maps'
    | '/api/public/subscribe'
    | '/api/public/unsubscribe'
    | '/api/webhooks/pop-up-announce'
    | '/api/webhooks/stripe'
    | '/checkout'
  id:
    | '__root__'
    | '/_app'
    | '/unsubscribe'
    | '/_app/blog'
    | '/_app/cart'
    | '/_app/our-story'
    | '/_app/pop-ups'
    | '/_app/shop'
    | '/_app/support'
    | '/_app/'
    | '/_app/blog_/$slug'
    | '/_app/checkout/return'
    | '/_app/shop_/$slug'
    | '/api/public/_healthz'
    | '/api/public/maps'
    | '/api/public/subscribe'
    | '/api/public/unsubscribe'
    | '/api/webhooks/pop-up-announce'
    | '/api/webhooks/stripe'
    | '/_app/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiPublicHealthzRoute: typeof ApiPublicHealthzRoute
  ApiPublicMapsRoute: typeof ApiPublicMapsRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiWebhooksPopUpAnnounceRoute: typeof ApiWebhooksPopUpAnnounceRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pop-ups': {
      id: '/_app/pop-ups'
      path: '/pop-ups'
      fullPath: '/pop-ups'
      preLoaderRoute: typeof AppPopUpsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/our-story': {
      id: '/_app/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof AppOurStoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/blog': {
      id: '/_app/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/checkout/': {
      id: '/_app/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AppCheckoutIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/pop-up-announce': {
      id: '/api/webhooks/pop-up-announce'
      path: '/api/webhooks/pop-up-announce'
      fullPath: '/api/webhooks/pop-up-announce'
      preLoaderRoute: typeof ApiWebhooksPopUpAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maps': {
      id: '/api/public/maps'
      path: '/api/public/maps'
      fullPath: '/api/public/maps'
      preLoaderRoute: typeof ApiPublicMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/_healthz': {
      id: '/api/public/_healthz'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/shop_/$slug': {
      id: '/_app/shop_/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof AppShopSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/checkout/return': {
      id: '/_app/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof AppCheckoutReturnRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/blog_/$slug': {
      id: '/_app/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBlogRoute: typeof AppBlogRoute
  AppCartRoute: typeof AppCartRoute
  AppOurStoryRoute: typeof AppOurStoryRoute
  AppPopUpsRoute: typeof AppPopUpsRoute
  AppShopRoute: typeof AppShopRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppCheckoutReturnRoute: typeof AppCheckoutReturnRoute
  AppShopSlugRoute: typeof AppShopSlugRoute
  AppCheckoutIndexRoute: typeof AppCheckoutIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBlogRoute: AppBlogRoute,
  AppCartRoute: AppCartRoute,
  AppOurStoryRoute: AppOurStoryRoute,
  AppPopUpsRoute: AppPopUpsRoute,
  AppShopRoute: AppShopRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppCheckoutReturnRoute: AppCheckoutReturnRoute,
  AppShopSlugRoute: AppShopSlugRoute,
  AppCheckoutIndexRoute: AppCheckoutIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiPublicHealthzRoute: ApiPublicHealthzRoute,
  ApiPublicMapsRoute: ApiPublicMapsRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiWebhooksPopUpAnnounceRoute: ApiWebhooksPopUpAnnounceRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
